### ISSUE TITLE
chi2 map

### ISSUE THREAD

**Issue by JenuC** [flimlib/flimj-ops#14]
We need the ch2-map/ goodness-of-fit map for the result array that comes from the fit (in addition to z,A,tau).

**Comment by Xanthorapedia** [comment]
Chi2-map is not turned on by default. You may try to turn it on with
```groovy
param.getChisqMap = true
```

**Comment by JenuC** [comment]
the script crahses
```groovy
# @ImageJ ij
# @ImgPlus img
op = ij.op()
import flimlib.flimj.FitParams
param = new FitParams()
param.transMap = img;

param.xInc=10.4/256
param.ltAxis = 2
param.getChisqMap = true
rldRslt = op.run("flim.fitRLD", param)
rldRslt.paramMap
```

**Comment by Xanthorapedia** [comment]
Can you post the error message? It runs fine on my FIJI.

**Comment by JenuC** [comment]
Did you get 4 images on the rldRslt? : Z,A,Tau and Chi ?

This was the error before. I had copied it on my clipboard.
```groovy.lang.MissingPropertyException: No such property: chi for class: flimlib.flimj.FitParams``` but, after restart of imagej now, I don't get this error. 😕 

anyway, my problem remains. I cannot access the result. The stack does not have 4 images as I would expect.

**Comment by JenuC** [comment]
Ah, my bad. The error message was created by a hidden "chi" that fell outside the comment section. Forget that error message.

@Xanthorapedia could you help me just get the chi-map image out?

**Comment by Xanthorapedia** [comment]
@JenuC No problem. You can just do
```groovy
rldRslt.chisqMap
```

**Comment by JenuC** [comment]
perfect. thank you.

**Comment by Xanthorapedia** [comment]
You bet!

**Comment by JenuC** [comment]
@Xanthorapedia : how can I get both parammap and chisqmap displayed in Fiji? when i call one, it closes the other.
```groovy 
result.chisqMap
result.paramMap
```

**Comment by JenuC** [comment]
solved. :smile: 
[result.chisqMap, result.paramMap]
