### ISSUE TITLE
Ability to save the current set of settings to some text file that can be used in scripts

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ops#15]
Ability to save the complete set of settings used to create the fit, including all those hidden from the user.

**Do we have the ability in ops to save and load all the settings required?** - If so then it is trivial.

Otherwise, writing the settings to a file such that they can be manually transferred into a script, or we can later write a reader, would be really helpful.

**Comment by ctrueden** [comment]
@paulbarber What do you mean by "hidden settings." With Ops, all parameters should be arguments to the op, so there should be no need for "settings" per se. There's only arguments to the functions. A script invoking flimj ops should contain all the information needed to reproduce. No?

If there are settings or state which is not part of the flimj op calls, but affects the quantification, let me know—this would be a bug in the flimj ops and need to be corrected.

**Comment by JenuC** [comment]
I thought this was intended for the GUI (flimj-ui).  The fitting from GUI is not currently reproducible unless the user makes note of all the fitting parameters selected.

**Comment by Xanthorapedia** [comment]
@paulbarber Hi Paul, I have added this feature. You can now check the "Save config" checkbox in the Export panel. That will save everything you need (except for binning) to a JSON text file. You may then load the JSON file into a `String` and recover the `FitParams` object with [`FitParams.fromJSON(str)`](https://github.com/flimlib/flimj-ops/blob/master/src/test/java/flimlib/flimj/MiscTest.java#L78).
