### ISSUE TITLE
kernel-fft in XYT files

### ISSUE THREAD

**Issue by JenuC** [flimlib/flimj-ops#6]
SQUARE_KERNEL in an sdt file would be a box filter that would sum three dimensions(that includes smoothing of the time curve). I am not completely sure if this is happening, but if an n-dim fft is used to bin the XYT file, I assume a 3D boxfilter is applied to the time dimension as well. Separate temporal and spatial binning.

**Comment by Xanthorapedia** [comment]
The kernel is defined as:
https://github.com/flimlib/flimj-ops/blob/adfa84d3963aeab6693b607710735c602dc53c02/src/main/java/flimlib/flimj/FlimOps.java#L25 The time dimension will have size 1 and thus receive no values from neighboring bins.

One potential hazard, however, is that this singleton dimension does not coincide with the time dimension of the dataset. However, I believe it is the users' responsibility to pass in the kernel with the correct directions, just in case they want to go with unusual binning schemes. Does this address your concern?

**Comment by JenuC** [comment]
I see. It is a 2D filter applied on the XYT stack. I was confused when you explained the kernel last week. Anyway, this is good. 
About users' responsibility in passing right kernel direction: I assume you are talking about calling ops with a wrong kernel, is it? I don't understand "directions" of kernel. could you give an example before I start to go imagining the possibilities? is it XYT vs YXT?

**Comment by Xanthorapedia** [comment]
Sure. What I meant by the direction of the kernel is simply that the user has to make sure the definition of axes of the kernel aligns with those of the dataset, regardless of the kernel sizes.
For example, if the user feeds in a dataset of funny axis order XTY and the kernel is of size 3x3x1, the fitting `op` will assume the user wants to bin along the X and T axes.

**Comment by JenuC** [comment]
Yeah. User errors may happen. In my opinion, we don't have to do input validation. But maybe later when there is a better standard for lifetime-data, we can revisit this.
